package lexer;

/**
 * This file is automatically generated<br>
 * - it contains the enumeration of all of the tokens
 */
public enum Tokens {
    BogusToken, Program, Int, Number, DateType,
    BOOLean, If, Then, Else, While,
    Doloop, Until, For, In, Break,
    Continue, Function, Return, Identifier, INTeger,
    NumberLit, DateLit, LeftBrace, RightBrace, LeftParen,
    RightParen, LeftBracket, RightBracket, Comma, Assign,
    Equal, NotEqual, Greater, GreaterEqual, Less,
    LessEqual, Plus, Minus, Or, And,
    Multiply, Divide, Comment
}
